CFLAGS=--std=c99 -D_GNU_SOURCE -Wall -g
LDFLAGS=-lcrypto
##LIBS=/usr/lib/libcrypto.a

.PHONY: all
all:  vali-xgg

.PHONY: clean
clean:
	rm -f  vali-cgg

# sign-xtp: sign-xtp.c 

# vali-xtp: vali-xtp.c .c

# .PRECIOUS: key.c
# key.c: genkey
# 	[ -f $@ ] || ./genkey $@

# genkey: genkey.c
# 	gcc -o $@ $(CFLAGS) $< $(LIBS)
