/****************************************************************************************
 * Gaggle is Copyright 2010, 2011, and 2012 by Kevin Hester of Geeksville Industries LLC,
 * a California limited liability corporation. 
 * 
 * Gaggle is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, either 
 * version 3 of the License, or (at your option) any later version.
 * 
 * Gaggle is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
 * PURPOSE.  See the GNU General Public License for more details. 
 * 
 * You should have received a copy of the GNU General Public License along with Gaggle 
 * included in this distribution in the manual (assets/manual/gpl-v3.txt). If not, see  
 * <http://www.gnu.org/licenses/> or at <http://gplv3.fsf.org>.
 ****************************************************************************************/
package com.geeksville.location;

import java.util.Arrays;
import java.util.Collection;

import com.geeksville.android.InMemoryCursor;

/**
 * Lets Cursor users see waypoints sorted a variety of ways
 * 
 * @author kevinh
 * 
 *         FIXME - implement deactivate
 */
public class WaypointCursor extends InMemoryCursor {

	public static final String KEY_DIST_PILOTX = "distx";
	public static final String KEY_DIST_PILOTY = "disty";

	private static final String[] colNames = {
			LocationLogDbAdapter.KEY_ROWID, // must be first to support updates
			LocationLogDbAdapter.KEY_LATITUDE, LocationLogDbAdapter.KEY_LONGITUDE,
			LocationLogDbAdapter.KEY_ALTITUDE,
			LocationLogDbAdapter.KEY_NAME,
			LocationLogDbAdapter.KEY_DESCRIPTION,
			LocationLogDbAdapter.KEY_WAYPOINT_TYPE, KEY_DIST_PILOTX, KEY_DIST_PILOTY };

	Collection<ExtendedWaypoint> src;

	/**
	 * The currently sorted list of waypoints (will be regenerated by requery())
	 */
	ExtendedWaypoint[] current;

	public WaypointCursor(Collection<ExtendedWaypoint> src) {
		super(colNames);

		this.src = src;

		current = new ExtendedWaypoint[src.size()];
		requery();
	}

	/**
	 * Get the waypoint this cursor is currently looking at
	 * 
	 * @return
	 */
	public ExtendedWaypoint getWaypoint() {
		return current[this.getPosition()];
	}

	/**
	 * 
	 * @see android.database.AbstractCursor#requery()
	 */
	@Override
	public boolean requery() {

		current = src.toArray(current);

		// FIXME - is there a faster way to do this?
		Arrays.sort(current, 0, getCount());

		return super.requery();
	}

	@Override
	protected boolean updateCurRow(int oldPosition, int newPosition, Object[] curRow) {

		ExtendedWaypoint w = current[newPosition];

		int colNum = 0;
		curRow[colNum++] = w.id;
		curRow[colNum++] = w.latitude;
		curRow[colNum++] = w.longitude;
		curRow[colNum++] = w.altitude;
		curRow[colNum++] = w.name;
		curRow[colNum++] = w.description;
		curRow[colNum++] = w.type.ordinal();
		curRow[colNum++] = w.distanceFromPilotX;
		curRow[colNum++] = w.distanceFromPilotY;

		return true;
	}

	@Override
	public int getCount() {
		return src.size();
	}
}
